### ISSUE TITLE
Unable to build locally

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-render#187]
So sorry to post this here, but I simply cannot get scratch-render to build under windows any longer.

I do this:
> git clone https://github.com/griffpatch/scratch-render
> cd scratch-render
> npm install

To which I get this warning...
```
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit  git+https://github.com/LLK/scratch-render-fonts.git resetting remote C:\Users\andrew.griffin\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-LLK-scratch-render-fonts-git-1eca31ed because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
```

Followed by this error:
```
    ERROR in ./node_modules/grapheme-breaker/src/GraphemeBreaker.js
    Module not found: Error: Can't resolve 'fs' in 'C:\Users\andrew.griffin\Documents\GitHub\scratch-render2\node_modules\grapheme-breaker\src'
     @ ./node_modules/grapheme-breaker/src/GraphemeBreaker.js 9:7-20
     @ ./src/util/text-wrapper.js
     @ ./src/util/svg-text-wrapper.js
     @ ./src/util/svg-text-bubble.js
     @ ./src/RenderWebGL.js
     @ ./src/index.js
     @ ./src/index-web.js

    ERROR in ./node_modules/linebreak/src/linebreaker.js
    Module not found: Error: Can't resolve 'fs' in 'C:\Users\andrew.griffin\Documents\GitHub\scratch-render2\node_modules\linebreak\src'
     @ ./node_modules/linebreak/src/linebreaker.js 7:7-20
     @ ./src/util/text-wrapper.js
     @ ./src/util/svg-text-wrapper.js
     @ ./src/util/svg-text-bubble.js
     @ ./src/RenderWebGL.js
     @ ./src/index.js
     @ ./src/index-web.js
```

And I just can't get passed it. It appears to not like an fs = require('fs'); ?
I'm sure you guys are too busy to point me in the right direction... I just wanted to lend a hand with debugging - but trying to set things up in windows seems very error prone sadly.

Griffpatch

**Comment by griffpatch** [comment]
I've tried updating to the latest version of node, and clearing down my npm caches, but I cannot get around the same issue: Why is the package 'fs' not available?

```
    ERROR in ./node_modules/grapheme-breaker/src/GraphemeBreaker.js
    Module not found: Error: Can't resolve 'fs' in 'C:\Users\griffpatch\Documents\GitHub\scratch-render\node_modules\grapheme-breaker\src'
     @ ./node_modules/grapheme-breaker/src/GraphemeBreaker.js 9:7-20
     @ ./src/util/text-wrapper.js
     @ ./src/util/svg-text-wrapper.js
     @ ./src/util/svg-text-bubble.js
     @ ./src/RenderWebGL.js
     @ ./src/index.js
     @ ./src/index-web.js

    ERROR in ./node_modules/linebreak/src/linebreaker.js
    Module not found: Error: Can't resolve 'fs' in 'C:\Users\griffpatch\Documents\GitHub\scratch-render\node_modules\linebreak\src'
     @ ./node_modules/linebreak/src/linebreaker.js 7:7-20
     @ ./src/util/text-wrapper.js
     @ ./src/util/svg-text-wrapper.js
     @ ./src/util/svg-text-bubble.js
     @ ./src/RenderWebGL.js
     @ ./src/index.js
     @ ./src/index-web.js
```
