### ISSUE TITLE
Unable to create scratch renderer in new project

### ISSUE THREAD

**Issue by SimonMeysman** [LLK/scratch-render#217]
### Expected Behavior

I installed the scratch-render in my project by calling npm install scratch-render and tried following the guide in the readme.md. I fail to be able to create an instance of the scratch renderer however.

### Actual Behavior

If I run the code as given in the readme, e.g. 
```
var canvas = document.getElementById('myStage');
var renderer = new require('scratch-render')(canvas);
```
I get the following error:
```
/home/osboxes/Documents/Github/demo-scratch/node_modules/scratch-render/dist/node/scratch-render.js:10445
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
                                                                                            ^

TypeError: Cannot call a class as a function
    at _classCallCheck (/home/osboxes/Documents/Github/demo-scratch/node_modules/scratch-render/dist/node/scratch-render.js:10445:99)
    at RenderWebGL (/home/osboxes/Documents/Github/demo-scratch/node_modules/scratch-render/dist/node/scratch-render.js:10529:9)
    at Object.<anonymous> (/home/osboxes/Documents/Github/demo-scratch/test_mad_hatter2.js:59:45)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
```

My first try was to split the instantiation and the require, as following:
```
var canvas = document.getElementById('myStage');
var render = new require('scratch-render');
var renderer = new render(canvas);
```
This however gives me a different error which is why I added this result:
```
/home/osboxes/Documents/Github/demo-scratch/node_modules/scratch-render/dist/node/scratch-render.js:643
	    if (typedArray instanceof WebGLBuffer) {
	                              ^

ReferenceError: WebGLBuffer is not defined
    at createBufferFromTypedArray (/home/osboxes/Documents/Github/demo-scratch/node_modules/scratch-render/dist/node/scratch-render.js:643:32)
    at /home/osboxes/Documents/Github/demo-scratch/node_modules/scratch-render/dist/node/scratch-render.js:904:21
    at Array.forEach (<anonymous>)
    at createAttribsFromArrays (/home/osboxes/Documents/Github/demo-scratch/node_modules/scratch-render/dist/node/scratch-render.js:883:26)
    at Object.createBufferInfoFromArrays (/home/osboxes/Documents/Github/demo-scratch/node_modules/scratch-render/dist/node/scratch-render.js:1141:17)
    at RenderWebGL._createGeometry (/home/osboxes/Documents/Github/demo-scratch/node_modules/scratch-render/dist/node/scratch-render.js:11605:37)
    at new RenderWebGL (/home/osboxes/Documents/Github/demo-scratch/node_modules/scratch-render/dist/node/scratch-render.js:10562:15)
    at Object.<anonymous> (/home/osboxes/Documents/Github/demo-scratch/test_mad_hatter2.js:61:20)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
```
### Steps to Reproduce

run the code above in an project that has scratch-render installed using npm. I have checked to make sure the canvas is found, so this is not the issue. My apologies if I made some rudimentary javascript/node.js mistake, I have mostly experience in Python, Java and C++.

### Operating System and Browser

I have tried this both on a Windows 10 home edition and an ubuntu 16.10

**Comment by rschamp** [comment]
Hi Simon, are you trying to instantiate an instance of scratch-render headlessly in Node? The renderer will probably not work outside of a browser environment, since it expects WebGL, which I believe is what you're seeing in the second case. I'm not sure exactly what the first error is caused by.

For an example of using the Renderer by itself, see https://github.com/LLK/scratch-vm/blob/00d6e9e8e7cff1328938c9c9c70a47abd1e7e227/src/playground/benchmark.js#L397-L401. For this example you should include `scratch-render/dist/web/scratch-render.js`, which should make the constructor available globally.

**Comment by SimonMeysman** [comment]
Hmm yes, I am indeed working with just node.js because I want to test scratch code server side (inside a docker somewhere) but I also want collision detection as this is an important test case, but it does not seem to work without a renderer attached to the vm. I do already have a working node canvas, but I'll look into getting WebGL server side. 

Thank you for the example, this wil help greatly. Should I leave this open as the first issue does not seem to be related to the fact that WebGL is missing?

**Comment by rschamp** [comment]
Probably both are caused by scratch-render not being runnable headlessly, they just have different stacks for some reason, so I think this is ok to close. Thanks for reporting!
