### ISSUE TITLE
Console errors when you add a new blank costume

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-render#242]
### Expected Behavior

No console errors

### Actual Behavior

Console errors:
![image](https://user-images.githubusercontent.com/2855464/36759896-e30df564-1be6-11e8-8733-54468f4144aa.png)
```
scratch-render.js:6534 WebGL: INVALID_VALUE: texImage2D: no canvas
setTextureFromElement @ scratch-render.js:6534
createTexture @ scratch-render.js:7142
(anonymous) @ scratch-render.js:15265
_drawFromImage @ scratch-render.js:11983
img.onload @ scratch-render.js:11951
scratch-render.js:10628 Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at Silhouette.update (http://localhost:8601/lib.min.js:125954:27)
    at http://localhost:8601/lib.min.js:130592:40
    at SvgRenderer._drawFromImage (http://localhost:8601/lib.min.js:127309:17)
    at Image.img.onload (http://localhost:8601/lib.min.js:127277:27)
update @ scratch-render.js:10628
(anonymous) @ scratch-render.js:15266
_drawFromImage @ scratch-render.js:11983
img.onload @ scratch-render.js:11951
2(index):1 [.Offscreen-For-WebGL-0000028A62AD21E0]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: Can not generate mips
253[.Offscreen-For-WebGL-0000028A62AD21E0]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
```

### Steps to Reproduce

At https://llk.github.io/scratch-gui/develop/
1. Go to costumes tab
2. Add a costume from paint editor (hover over the add costume button, and pick the paintbrush)

I think this is caused by our fix for the size of the SVG that is being sent from the paint editor to the renderer. Now we can send 0 width SVGs. So should the renderer accept size 0 SVGs, or should we send some minimum sized blank SVG from paint?
@cwillisf 

### Operating System and Browser

Windows 10 Chrome

**Comment by fsih** [comment]
I think this is the same issue as https://github.com/LLK/scratch-render/issues/239 , but it's more critical now that 0x0 costumes are easy to make.

**Comment by fsih** [comment]
I think this is caused by our fix for the size of the SVG that is being sent from the paint editor to the renderer. Now we can send 0 width SVGs. So should the renderer accept size 0 SVGs, or should we send some minimum sized blank SVG from paint?
@cwillisf
