### ISSUE TITLE
WebGL: INVALID_VALUE: texImage2D: no canvas

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-render#244]
### Steps to Reproduce

Play https://llk.github.io/scratch-gui/develop/#204674478 past the first 3 cars
Eventually you will receive errors in the console (all are warnings except for the DOMException):
```
WebGL: INVALID_VALUE: texImage2D: no canvas
S @ lib.min.js:84

Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at e.value (https://llk.github.io/scratch-gui/develop/lib.min.js:84:76030)
    at https://llk.github.io/scratch-gui/develop/lib.min.js:84:494503
    at e.value (https://llk.github.io/scratch-gui/develop/lib.min.js:84:90192)
    at Image.l.onload (https://llk.github.io/scratch-gui/develop/lib.min.js:84:89643)

[.Offscreen-For-WebGL-0x7fe1040df000]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: Can not generate mips

[Deprecation] AudioParam value setter will become equivalent to AudioParam.setValueAtTime() in M65, around March 2018  See https://webaudio.github.io/web-audio-api/#dom-audioparam-value for more details.
value @ lib.min.js:68

(253 times:) [.Offscreen-For-WebGL-0x7fe1040df000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
```

### Operating System and Browser
Chrome  64.0.3282.186 MacOS 10.13.3

**Comment by rachel-fenichel** [comment]
Also spotted on https://preview.scratch.mit.edu/#207768440

```
Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at e.value (https://preview.scratch.mit.edu/lib.min.js:84:76030)
    at https://preview.scratch.mit.edu/lib.min.js:84:494503
    at e.value (https://preview.scratch.mit.edu/lib.min.js:84:90192)
    at Image.l.onload (https://preview.scratch.mit.edu/lib.min.js:84:89643)
```

**Comment by simeonsoden** [comment]
Still getting this! Any fixes?

**Comment by thisandagain** [comment]
This now appears to be resolved on `develop`. Closing.
