### ISSUE TITLE
TypeError - Cannot read property 'getFastBounds' of undefined

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-render#78]
### Error
```
Uncaught TypeError: Cannot read property 'getFastBounds' of undefined
    at http://llk.github.io/scratch-vm/vendor.js:29326:49
    at Array.filter (native)
    at RenderWebGL._filterCandidatesTouching (http://llk.github.io/scratch-vm/vendor.js:29322:42)
    at RenderWebGL.isTouchingDrawables (http://llk.github.io/scratch-vm/vendor.js:29134:34)
    at RenderedTarget.isTouchingSprite (http://llk.github.io/scratch-vm/scratch-vm.js:8457:26)
    at Scratch3SensingBlocks.touchingObject (http://llk.github.io/scratch-vm/scratch-vm.js:15534:28)
    at execute (http://llk.github.io/scratch-vm/scratch-vm.js:16145:30)
    at Sequencer.stepThread (http://llk.github.io/scratch-vm/scratch-vm.js:17188:9)
    at Sequencer.stepThreads (http://llk.github.io/scratch-vm/scratch-vm.js:17146:22)
    at Runtime._step (http://llk.github.io/scratch-vm/scratch-vm.js:16830:38)
    at Runtime.<anonymous> (http://llk.github.io/scratch-vm/scratch-vm.js:17069:14)
```

### Steps to Reproduce

- Load testing project http://llk.github.io/scratch-vm/#141694680
- Press "Start"
- Look at JavaScript console

### Operating System and Browser

Mac OS 10.12.2  |  Chrome 56.0.2924.76 (64-bit)

**Comment by SillyInventor** [comment]
Seems that you're not disposing of the object in the clones array of the relevant sprite when deleting clones.

**Comment by jwzimmer** [comment]
Several people ran into this during the Catch Game internal playtest (6/2/17).

Jie reported:
> Something dealing with clones seems to make everything freeze (not updating).  Error message on javascript console mentions 'getFastBounds' of undefined.  I also left an "increase pitch" block on for a long time so that may have also gone out of bounds somehow?

<img width="901" alt="screen shot 2017-06-05 at 9 15 06 am" src="https://cloud.githubusercontent.com/assets/1320456/26785287/84d90428-49cf-11e7-9004-17f5b5b8f546.png">
